
'use server';

/**
 * @fileOverview This file defines a Genkit flow for refining nutritional analysis using natural language prompts.
 *
 * refineNutritionalAnalysis - A function that takes the initial analysis and refinement instructions to produce a refined analysis.
 * RefineNutritionalAnalysisInput - The input type for the refineNutritionalAnalysis function.
 * RefineNutritionalAnalysisOutput - The return type for the refineNutritionalAnalysis function.
 */

import { ai } from '@/ai/index';
import {z} from 'genkit';
import { AnalyzeIndianFoodImageOutputSchema as NutritionalAnalysisSchema } from '@/lib/schemas';
import { ModelId } from '@/lib/types';

const RefineNutritionalAnalysisInputSchema = z.object({
  initialAnalysis: NutritionalAnalysisSchema.describe('The initial nutritional analysis generated by the AI.'),
  refinementInstruction: z.string().describe('Natural language instructions to refine the initial nutritional analysis.'),
});
export type RefineNutritionalAnalysisInput = z.infer<
  typeof RefineNutritionalAnalysisInputSchema
>;

const RefineNutritionalAnalysisOutputSchema = z.object({
  refinedAnalysis: NutritionalAnalysisSchema.describe('The refined nutritional analysis after applying the instructions.'),
  responseText: z.string().describe('A short, friendly message confirming the update.'),
  modelId: z.string().optional().describe('The model used for refinement.'),
});
export type RefineNutritionalAnalysisOutput = z.infer<
  typeof RefineNutritionalAnalysisOutputSchema
>;

export async function refineNutritionalAnalysis(
  input: RefineNutritionalAnalysisInput,
  modelId: ModelId
): Promise<RefineNutritionalAnalysisOutput> {
  const result = await refineNutritionalAnalysisFlow(input, { context: { modelId } });
  return { ...result, modelId };
}

const geminiPromptTemplate = `
You are a nutritional assistant. Your task is to refine a nutrition breakdown based on the user's feedback.

Here is the current analysis:
{{{json initialAnalysis}}}

Here are the user's instructions for refinement:
"{{{refinementInstruction}}}"

Based on these instructions, you MUST update the JSON data. For example, if the user says "the portion of rice was smaller", you should reduce the weight_g, calories, and macros for the rice item and update the totals. If they say "that wasn't paneer, it was tofu", you must replace the paneer item with a tofu item, recalculating everything accordingly.

Your response must be a valid JSON object that strictly follows this format:
{
  "refinedAnalysis": { // The entire updated nutritional analysis object, with all totals recalculated.
    "items": [...],
    "total_calories": ...,
    "total_macros": { ... },
    "confidence_score": ...,
    "food_type": "...",
    "summary": "..."
  },
  "responseText": "A short, friendly message to the user confirming the changes you made. For example: 'I've adjusted the portion size for you!'"
}
`;

const gemmaPromptTemplate = `You are a nutritional assistant. Your task is to refine a nutrition breakdown based on the user's feedback and return a single, raw JSON object. Do not add any other text.

Here is the current analysis:
{{{json initialAnalysis}}}

Here are the user's instructions for refinement:
"{{{refinementInstruction}}}"

Your JSON output MUST have the following structure. You MUST populate both 'refinedAnalysis' and 'responseText'.
{
  "refinedAnalysis": {
    "items": [
      {
        "name": "...",
        "weight": ...,
        "unit": "g" or "ml",
        "calories": ...,
        "macros": { "protein": ..., "carbs": ..., "fat": ... }
      }
    ],
    "total_calories": ...,
    "total_macros": { "protein": ..., "carbs": ..., "fat": ... },
    "confidence_score": ...,
    "food_type": "prepared" or "packaged",
    "summary": "..."
  },
  "responseText": "A short, friendly message confirming your changes."
}
Update the 'refinedAnalysis' object with the corrected data, recalculating all totals. Do not wrap the JSON in markdown.`;


const refineNutritionalAnalysisFlow = ai.defineFlow(
  {
    name: 'refineNutritionalAnalysisFlow',
    inputSchema: RefineNutritionalAnalysisInputSchema,
    outputSchema: z.object({
      refinedAnalysis: NutritionalAnalysisSchema,
      responseText: z.string(),
    }),
  },
  async (input, { context }) => {
    const modelId = context?.modelId || 'gemini-2.5-flash';
    const model = `googleai/${modelId}`;

    if (modelId.startsWith('gemma')) {
        const llmResponse = await ai.generate({
            prompt: gemmaPromptTemplate,
            model,
            promptParams: input,
        });
        let rawJson = llmResponse.text;
        if (rawJson.startsWith('```json')) {
          rawJson = rawJson.substring(7, rawJson.length - 3).trim();
        }
        try {
            const parsed = JSON.parse(rawJson);
            // The schema here should match what we expect from Gemma's output format
            return z.object({ 
                refinedAnalysis: NutritionalAnalysisSchema, 
                responseText: z.string() 
            }).parse(parsed);
        } catch(e) {
            console.error("Failed to parse Gemma JSON:", rawJson, e);
            throw new Error(`Gemma returned invalid JSON. Raw output: ${rawJson}`);
        }

    } else { // Is a Gemini model
        const prompt = ai.definePrompt({
            name: 'refineNutritionalAnalysisPrompt',
            input: {schema: RefineNutritionalAnalysisInputSchema},
            output: {schema: z.object({
                refinedAnalysis: NutritionalAnalysisSchema,
                responseText: z.string(),
            })},
            prompt: geminiPromptTemplate,
        });

        const {output} = await prompt(input, { model });
        if (!output) {
          throw new Error("Refinement failed to produce an output.");
        }
        return output;
    }
  }
);
