'use server';

/**
 * @fileOverview This file defines a Genkit flow for refining nutritional analysis using natural language prompts.
 *
 * refineNutritionalAnalysis - A function that takes the initial analysis and refinement instructions to produce a refined analysis.
 * RefineNutritionalAnalysisInput - The input type for the refineNutritionalAnalysis function.
 * RefineNutritionalAnalysisOutput - The return type for the refineNutritionalAnalysis function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RefineNutritionalAnalysisInputSchema = z.object({
  initialAnalysis: z
    .string()
    .describe('The initial nutritional analysis generated by the AI.'),
  refinementInstructions: z
    .string()
    .describe(
      'Natural language instructions to refine the initial nutritional analysis.'
    ),
});
export type RefineNutritionalAnalysisInput = z.infer<
  typeof RefineNutritionalAnalysisInputSchema
>;

const RefineNutritionalAnalysisOutputSchema = z.object({
  refinedAnalysis: z
    .string()
    .describe('The refined nutritional analysis after applying the instructions.'),
});
export type RefineNutritionalAnalysisOutput = z.infer<
  typeof RefineNutritionalAnalysisOutputSchema
>;

export async function refineNutritionalAnalysis(
  input: RefineNutritionalAnalysisInput
): Promise<RefineNutritionalAnalysisOutput> {
  return refineNutritionalAnalysisFlow(input);
}

const prompt = ai.definePrompt({
  name: 'refineNutritionalAnalysisPrompt',
  input: {schema: RefineNutritionalAnalysisInputSchema},
  output: {schema: RefineNutritionalAnalysisOutputSchema},
  prompt: `You are an expert nutritionist. You will receive an initial nutritional analysis of a meal and instructions on how to refine it.

Initial Analysis: {{{initialAnalysis}}}

Refinement Instructions: {{{refinementInstructions}}}

Based on the initial analysis and the refinement instructions, generate a refined nutritional analysis.

Refined Analysis:`,
});

const refineNutritionalAnalysisFlow = ai.defineFlow(
  {
    name: 'refineNutritionalAnalysisFlow',
    inputSchema: RefineNutritionalAnalysisInputSchema,
    outputSchema: RefineNutritionalAnalysisOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
