
'use server';

/**
 * @fileOverview This file defines a Genkit flow for refining nutritional analysis using natural language prompts.
 *
 * refineNutritionalAnalysis - A function that takes the initial analysis and refinement instructions to produce a refined analysis.
 * RefineNutritionalAnalysisInput - The input type for the refineNutritionalAnalysis function.
 * RefineNutritionalAnalysisOutput - The return type for the refineNutritionalAnalysis function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { AnalyzeIndianFoodImageOutputSchema as NutritionalAnalysisSchema } from '@/lib/schemas';

const RefineNutritionalAnalysisInputSchema = z.object({
  initialAnalysis: NutritionalAnalysisSchema.describe('The initial nutritional analysis generated by the AI.'),
  refinementInstruction: z.string().describe('Natural language instructions to refine the initial nutritional analysis.'),
});
export type RefineNutritionalAnalysisInput = z.infer<
  typeof RefineNutritionalAnalysisInputSchema
>;

const RefineNutritionalAnalysisOutputSchema = z.object({
  refinedAnalysis: NutritionalAnalysisSchema.describe('The refined nutritional analysis after applying the instructions.'),
  responseText: z.string().describe('A short, friendly message confirming the update.'),
});
export type RefineNutritionalAnalysisOutput = z.infer<
  typeof RefineNutritionalAnalysisOutputSchema
>;

export async function refineNutritionalAnalysis(
  input: RefineNutritionalAnalysisInput
): Promise<RefineNutritionalAnalysisOutput> {
  return refineNutritionalAnalysisFlow(input);
}

const prompt = ai.definePrompt({
  name: 'refineNutritionalAnalysisPrompt',
  input: {schema: RefineNutritionalAnalysisInputSchema},
  output: {schema: RefineNutritionalAnalysisOutputSchema},
  prompt: `
    You are a nutritional assistant. Your task is to refine a nutrition breakdown based on the user's feedback.

    Here is the current analysis:
    {{{json initialAnalysis}}}

    Here are the user's instructions for refinement:
    "{{{refinementInstruction}}}"

    Based on these instructions, you MUST update the JSON data. For example, if the user says "the portion of rice was smaller", you should reduce the weight_g, calories, and macros for the rice item and update the totals. If they say "that wasn't paneer, it was tofu", you must replace the paneer item with a tofu item, recalculating everything accordingly.

    Your response must be a valid JSON object that strictly follows this format:
    {
      "refinedAnalysis": { // The entire updated nutritional analysis object, with all totals recalculated.
        "items": [...],
        "total_calories": ...,
        "total_macros": { ... },
        "confidence_score": ...,
        "food_type": "...",
        "summary": "..."
      },
      "responseText": "A short, friendly message to the user confirming the changes you made. For example: 'I've adjusted the portion size for you!'"
    }
  `,
});

const refineNutritionalAnalysisFlow = ai.defineFlow(
  {
    name: 'refineNutritionalAnalysisFlow',
    inputSchema: RefineNutritionalAnalysisInputSchema,
    outputSchema: RefineNutritionalAnalysisOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    if (!output) {
      throw new Error("Refinement failed to produce an output.");
    }
    return output;
  }
);
